steps:
# Docker Build
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', '${_IMAGE_NAME}', '.' ]

# Docker push to Artifact Registry
- name: "gcr.io/cloud-builders/docker"
  args: ["push", "${_IMAGE_NAME}"]

# Deploy to Cloud Run
- name: "gcr.io/google.com/cloudsdktool/cloud-sdk:slim"
  entrypoint: gcloud
  args:
    [
      "run",
      "deploy",
      "${_BASE_NAME}",
      "--image",
      "${_IMAGE_NAME}",
      "--region",
      "asia-northeast1",
      "--platform",
      "managed",
      "--allow-unauthenticated",
    ]

images:
- "${_IMAGE_NAME}"

# ユーザー定義変数
substitutions:
  _SERVICE_NAME: "hello-world"
  _IMAGE_NAME: "asia-northeast1-docker.pkg.dev/${PROJECT_ID}/${TRIGGER_NAME}/${_BASE_NAME}:${SHORT_SHA}"
